{% set name = "bluesky-adaptive" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 00809e52e170e5b962f94ecfbcbc56aa5ac515d878809c8fd0ca121c380c4ebe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bluesky
    - bluesky-live
    - bluesky-widgets
    - bluesky-kafka
    - bluesky-queueserver-api
    - xkcdpass
    - tiled
    - numpy
    - pydantic

test:
  imports:
    - bluesky_adaptive
    - bluesky_adaptive.adjudicators
    - bluesky_adaptive.adjudicators.base
    - bluesky_adaptive.adjudicators.msg
    - bluesky_adaptive.agents
    - bluesky_adaptive.agents.base
    - bluesky_adaptive.server

  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bluesky/bluesky-adaptive
  summary: Tools for writing adaptive plans
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maffettone
    - mrakitin
